# NumPy

## 1. Installation of NumPy

In [19]:
!pip install numpy

     ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
      --------------------------------------- 0.0/2.1 MB 1.3 MB/s eta 0:00:02
     - -------------------------------------- 0.1/2.1 MB 1.1 MB/s eta 0:00:02
     --- ------------------------------------ 0.2/2.1 MB 1.5 MB/s eta 0:00:02
     ----- ---------------------------------- 0.3/2.1 MB 1.5 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.9 MB/s eta 0:00:01
     ------------ --------------------------- 0.6/2.1 MB 2.5 MB/s eta 0:00:01
     -------------------- ------------------- 1.0/2.1 MB 3.3 MB/s eta 0:00:01
     -------------------- ------------------- 1.1/2.1 MB 3.4 MB/s eta 0:00:01
     --------------------------- ------------ 1.4/2.1 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------  2.1/2.1 MB 4.7 MB/s eta 0:00:01
     ---------------------------------------- 2.1/2.1 MB 4.5 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1

## 2. Import NumPy

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## 3. Checking NumPy Version

In [26]:
import numpy as np

print(np.__version__)

1.24.2


## 4. Create a NumPy ndarray Object

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr2 = np.array((6, 7, 8, 9, 10))

print(arr)
print(type(arr))

print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 6  7  8  9 10]
<class 'numpy.ndarray'>


## 5. Dimensions in Arrays

### 0-D Arrays (Scalars)

In [29]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D Arrays (Vectors)

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays (Matrices)

In [31]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays (Tensors)

In [33]:
import numpy as np

arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[1, 2, 3],
                 [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## 6. Check Number of Dimensions?

In [35]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 7. Higher Dimensional Arrays

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## 8. Access Array Elements

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


### Access 2-D Arrays

In [40]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


### Access 3-D Arrays

In [41]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

### Negative Indexing

In [42]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
