# 2 Python cơ bản

## 2.1 Kiểu dữ liệu cơ bản

Giống với các ngôn ngữ lập trình khác, Python cũng có các kiểu dữ liệu cơ bản như integers (số
nguyên), floats (số thực), booleans (kiểu dữ liệu True/False) và strings (chuỗi)

### 2.1.1 Số

In [ ]:
Số nguyên và số thực dùng như các ngôn ngữ khác

x = 3
print(type(x)) # Prints "<class 'int'>"
print(x) # Prints "3"
print(x + 1) # Cộng; prints "4"
print(x - 1) # Trừ; prints "2"
print(x * 2) # Nhân; prints "6"
print(x ** 2) # Lũy thừa; prints "9"
x += 1
print(x) # Prints "4"
x *= 2
print(x) # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

### 2.1.2 Phép tính logic

In [ ]:
Python có các phép tính logic nhưng dùng các từ tiếng anh (and, or) thay cho kí hiệu (&&, ||):
    
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # AND; prints "False"
print(t or f) # OR; prints "True"
print(not t) # NOT; prints "False"
print(t != f) # XOR; prints "True"

### 2.1.3 Chuỗi

In [ ]:
Python có hỗ trợ dạng chuỗi

hello = 'hello' # gán giá trị chuỗi cho biến, chuỗi đặt trong 2 dấu '
world = "world" # chuỗi cũng có thể đặt trong dấu ".
print(hello) # Prints "hello"
print(len(hello)) # Độ dài chuỗi; prints "5"
hw = hello + ' ' + world # Nối chuỗi bằng dấu +
print(hw) # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12) # Cách format chuỗi
print(hw12) # prints "hello world 12"

Kiểu string có rất nhiều method để xử lý chuỗi

s = "hello"
print(s.capitalize()) # Viết hoa chữ cái đầu; prints "Hello"
print(s.upper()) # Viết hoa tất cả các chữ; prints "HELLO"
print(s.replace('l', '(ell)')) # Thay thế chuỗi; prints "he(ell)(ell)o"
print(' world '.strip()) # Bỏ đi khoảng trắng ở đầu và cuối chuỗi; prints "world"

## 2.2 Containers

Python có một số container như: lists, dictionaries,...

### 2.2.1 List

In [ ]:
List trong Python giống như mảng (array) nhưng không cố định kích thước và có thể chứa nhiều
kiểu dữ liệu khác nhau trong 1 list.

xs = [3, 1, 2] # Tạo 1 list
print(xs, xs[2]) # Prints "[3, 1, 2] 2"
print(xs[-1]) # Chỉ số âm là đếm phần tử từ cuối list lên; prints "2"
xs[2] = 'foo' # List có thể chứa nhiều kiểu phần tử khác nhau
print(xs) # Prints "[3, 1, 'foo']"
xs.append('bar') # Thêm phần tử vào cuối list
print(xs) # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop() # Bỏ đi phần tử cuối cùng khỏi list và trả về phần tử đấy
print(x, xs) # Prints "bar [3, 1, 'foo']"

Slicing Thay vì lấy từng phần tử một trong list thì python hỗ trợ truy xuất nhiều phần tử 1 lúc gọi là
slicing.

nums = list(range(5)) # range sinh ta 1 list các phần tử
print(nums) # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4]) # Lấy phần tử thứ 2->4, python chỉ số mảng từ 0;
print(nums[2:]) # Lấy từ phần tử thứ 2 đến hết; prints "[2, 3, 4]"
print(nums[:2]) # Lấy từ đầu đến phần tử thứ 2; prints "[0, 1]"
print(nums[:]) # Lấy tất cả phần tử trong list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1]) # Lấy từ phần tử đầu đến phần tử gần cuối trong list; prints "[nums[2:4] = [8, 9] # Gán giá trị mới cho phần tử trong mảng từ vị trí 2->4
print(nums) # Prints "[0, 1, 8, 9, 4]"

Loops Để duyệt và in ra các phần tử trong list

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", in mỗi thành phần trong list 1 dòng

### 2.2.2 Dictionaries

In [ ]:
Dictionaries lưu thông tin dưới dạng key, value.

d = {'cat': 'cute', 'dog': 'furry'} # Tạo dictionary, các phần tử dạng key:value
print(d['cat']) # Lấy ra value của key 'cat' trong dictionary; prints "cute"
print('cat' in d) # Kiểm tra key có trong dictionary không; prints "True"
d['fish'] = 'wet' # Gán key, value, d[key] = value
print(d['fish']) # Prints "wet"
# print(d['monkey']) # Lỗi vì key 'monkey' không trong dictionary;
del d['fish'] # Xóa phần tử key:value từ dictionary

Loop Duyệt qua các phần tử trong dictionary

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

## 2.3 Function

In [ ]:
Function là một khối code python được thực hiện một hoặc một số chức năng nhất định. Function
trong python được định nghĩa với keyword def.

# Hàm có input là 1 số và output xem số đấy âm, dương hay số 0
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
    
for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

## 2.4 Sử dụng Numpy

In [ ]:
Vì Python là scripting language nên không thích hợp cho ML, Numpy giải quyết vấn đề trên bằng
cách xây dựng 1 thư viện viết bằng C nhưng có interface Python. Như vậy Numpy cộng hưởng 2 ưu
điểm của 2 ngôn ngữ: nhanh như C và đơn giản như Python. Điều này giúp ích rất nhiều cho cộng
đồng Machine Learning trên Python.
Mảng trong numpy gồm các phần tử có dùng kiểu giá trị, chỉ số không âm được bắt đầu từ 0, số
chiều được gọi là rank của mảng Numpy, và shape là một tuple các số nguyên đưa ra kích thước của
mảng theo mỗi chiều.

import numpy as np

a = np.array([1, 2, 3]) # Tạo array 1 chiều
print(type(a)) # Prints "<class 'numpy.ndarray'>"
print(a.shape) # Prints "(3,)"
print(a[0], a[1], a[2]) # Prints "1 2 3"
a[0] = 5 # Thay đổi phần tử vị trí số 0
print(a) # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]]) # Tạo array 2 chiều
print(b.shape) # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # Prints "1 2 4"

Ngoài ra có những cách khác để tạo array với giá trị mặc định

import numpy as np

a = np.zeros((2,2)) # Tạo array với tất cả các phần tử 0
print(a)            # Prints "[[ 0. 0.]
                    #          [ 0. 0.]]"
    
b = np.ones((1,2)) # Tạo array với các phần từ 1
print(b)           # Prints "[[ 1. 1.]]"

c = np.full((2,2), 7) # Tạo array với các phần tử 7
print(c)              # Prints "[[ 7. 7.]
                      #          [ 7. 7.]]"

d = np.eye(2) # Tạo identity matrix kích thước 2*2
print(d)      # Prints "[[ 1. 0.]
              #          [ 0. 1.]]"

e = np.random.random((2,2)) # Tạo array với các phần tử được tạo ngẫu nhiên
print(e)                    # Might print "[[ 0.91940167 0.08143941]
                            #               [ 0.68744134 0.87236687]]"

### 2.4.1 Array indexing

In [ ]:
Tương tự như list, numpy array cũng có thể slice. Tuy nhiên vì numpy array có nhiều chiều, nên khi
dùng slice phải chỉ định rõ chiều nào.

import numpy as np

# Tạo array 2 chiều với kích thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Dùng slide để lấy ra subarray gồm 2 hàng đầu tiên (1 & 2) và 2 cột (2 & 3)
# Output là array kích thước 2*2
# [[2 3]
# [6 7]]
b = a[:2, 1:3]

print(a[0, 1]) # Prints "2"
a[0, 1] = 77 # Chỉnh sửa phần tử trong array
print(a[0, 1]) # Prints "77"

Bên cạnh đó cũng có thể dùng các chỉ số với slice index. Tuy nhiên số chiều array sẽ giảm đi.

import numpy as np

# Tạo array 2 chiều kích thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :] # Lấy ra hàng thứ 2 trong a, output array 1 chiều
row_r2 = a[1:2, :] # Lấy ra hàng thứ 1&2 trong a, output array 2 chiều
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"

### 2.4.2 Các phép tính trên array

In [ ]:
Các phép tính với ma trận được hỗ trợ trên numpy

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Tính tổng
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Phép trừ
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Phép nhân element-wise
# [[ 5.0 12.0]
# [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Phép chia element-wise
# [[ 0.2 0.33333333]
# [ 0.42857143 0.5 ]]
print(x / y)
print(np.divide(x, y))

# Tính căn bậc hai
# [[ 1. 1.41421356]
# [ 1.73205081 2. ]]
print(np.sqrt(x))

* dùng để nhân element-wise chứ không phải nhân ma trận thông thường. Thay vào đó dùng np.dot
để nhân ma trận.

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Nhân ma trận, output số 219
print(v.dot(w))
print(np.dot(v, w))

# Nhân ma trận; output ma trận 2*2
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

Numpy cũng hỗ trợ tính tổng array theo các chiều khác nhau

import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x)) # Tính tổng tất cả phần tử trong array; prints "10"
print(np.sum(x, axis=0)) # Tính tổng phần tử mỗi hàng; prints "[4 6]"
print(np.sum(x, axis=1)) # Tính tổng phần tử mỗi cột; prints "[3 7]"

## 2.5 Broadcasting

In [ ]:
Broadcasting là một kĩ thuật cho phép numpy làm việc với các array có shape khác nhau khi thực
hiện các phép toán.

import numpy as np

# Cộng vector v với mỗi hàng của ma trận x, kết quả lưu ở ma trận y.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Tạo 1 array có chiều giống x

# Dùng loop để vector v với mỗi hàng của ma trận
for i in range(4):
    y[i, :] = x[i, :] + v
    
# Kết quả của y
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
print(y)